.TH openVFSFuse 1 "JANUARY 2023" "User Manuals"
.SH NAME
openVFSFuse \- Virtual Filesystem for cloud files incl. monitoring
.SH SYNOPSIS
.B openvfsfuse [-fp] [-c
.I config-file
.B ] [-l
.I log-file
.B ]
.I directory
.B ...
.SH DESCRIPTION
.B openvfsfuse
is a transparent fuse-filesystem which provides virtual file handling for the free desktop. It is based on code called loggedfs which offers filesystem logging.

.SH OPTIONS
.IP -f
Do not start as a daemon. Write logs to stdout if no log file is specified.
.IP "-c config-file"
Use the
.I config-file
to filter what you want to log.
.IP "-l log-file"
Use the
.I log-file
to write logs to. If no log file is specified then logs are only written to syslog or to stdout, depending on -f.
.IP -p
Allow every users to see.
.SH FILES
.I /etc/fuse.conf
.RS
The system wide configuration file.
.RE
.SH AUTHOR
Remi Flament <remipouak@gmail.com>
Klaas Freitag <kfreitag@owncloud.com>
.SH "SEE ALSO"
.BR fusermount (1)
